name: CD

on:
    workflow_dispatch:


permissions:
  contents: write

jobs:
  
  build:
    permissions: write-all

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      SolutionName: Paulov.Tarkov.Minimal                              
      CSProj: Paulov.Tarkov.Minimal.csproj               

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0


    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore all projects
    - name: dotnet Restore
      run: dotnet restore

    # Publish the Launcher as Self-Contained Single-File
    - name: dotnet Publish
      run: |
        mkdir ${{ env.SolutionName }}-${{ matrix.configuration }}
        dotnet build ${{ env.CSProj }} -c ${{ matrix.configuration }} -o ${{ env.SolutionName }}-${{ matrix.configuration }}

    - name: Get version from DLL
      id: extract-version
      run: |
        $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("${{ env.SolutionName }}-${{ matrix.configuration }}\StayInTarkov.dll").ProductVersion
        echo "::set-output name=VERSION::$version"


    - name: Display Version in Logs
      run: echo "The extracted version is ${{ steps.extract-version.outputs.VERSION }}"

    - name: Zip remaining files
      run: |
          Compress-Archive -Path ${{ env.SolutionName }}-${{ matrix.configuration }} -DestinationPath ${{ env.SolutionName }}-${{ matrix.configuration }}.zip
 
    # Create release as draft from the compressed file
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ matrix.configuration == 'Release' }}
      with:
          draft: true
          generate_release_notes: true
          files: ${{ env.SolutionName }}-${{ matrix.configuration }}.zip
          tag_name: Paulov.Tarkov.Minimal-${{ steps.extract-version.outputs.VERSION }}
